[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/745241431",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/6003#issuecomment-745241431",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/6003",
        "id": 745241431,
        "node_id": "MDEyOklzc3VlQ29tbWVudDc0NTI0MTQzMQ==",
        "user": {
            "login": "j-paulus",
            "id": 20085087,
            "node_id": "MDQ6VXNlcjIwMDg1MDg3",
            "avatar_url": "https://avatars.githubusercontent.com/u/20085087?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/j-paulus",
            "html_url": "https://github.com/j-paulus",
            "followers_url": "https://api.github.com/users/j-paulus/followers",
            "following_url": "https://api.github.com/users/j-paulus/following{/other_user}",
            "gists_url": "https://api.github.com/users/j-paulus/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/j-paulus/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/j-paulus/subscriptions",
            "organizations_url": "https://api.github.com/users/j-paulus/orgs",
            "repos_url": "https://api.github.com/users/j-paulus/repos",
            "events_url": "https://api.github.com/users/j-paulus/events{/privacy}",
            "received_events_url": "https://api.github.com/users/j-paulus/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2020-12-15T11:54:40Z",
        "updated_at": "2020-12-15T11:54:40Z",
        "author_association": "NONE",
        "body": "Update: The exact same problem is present in ONNX Runtime 1.6.0.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/745241431/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/789517762",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/6003#issuecomment-789517762",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/6003",
        "id": 789517762,
        "node_id": "MDEyOklzc3VlQ29tbWVudDc4OTUxNzc2Mg==",
        "user": {
            "login": "j-paulus",
            "id": 20085087,
            "node_id": "MDQ6VXNlcjIwMDg1MDg3",
            "avatar_url": "https://avatars.githubusercontent.com/u/20085087?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/j-paulus",
            "html_url": "https://github.com/j-paulus",
            "followers_url": "https://api.github.com/users/j-paulus/followers",
            "following_url": "https://api.github.com/users/j-paulus/following{/other_user}",
            "gists_url": "https://api.github.com/users/j-paulus/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/j-paulus/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/j-paulus/subscriptions",
            "organizations_url": "https://api.github.com/users/j-paulus/orgs",
            "repos_url": "https://api.github.com/users/j-paulus/repos",
            "events_url": "https://api.github.com/users/j-paulus/events{/privacy}",
            "received_events_url": "https://api.github.com/users/j-paulus/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-03-03T07:57:19Z",
        "updated_at": "2021-03-03T07:57:19Z",
        "author_association": "NONE",
        "body": "Update: The problem persists in ONNX Runtime 1.7.0 with DML 1.4.2.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/789517762/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1055086140",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/6003#issuecomment-1055086140",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/6003",
        "id": 1055086140,
        "node_id": "IC_kwDOCVq1mM4-41Y8",
        "user": {
            "login": "fdwr",
            "id": 1809166,
            "node_id": "MDQ6VXNlcjE4MDkxNjY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1809166?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fdwr",
            "html_url": "https://github.com/fdwr",
            "followers_url": "https://api.github.com/users/fdwr/followers",
            "following_url": "https://api.github.com/users/fdwr/following{/other_user}",
            "gists_url": "https://api.github.com/users/fdwr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fdwr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fdwr/subscriptions",
            "organizations_url": "https://api.github.com/users/fdwr/orgs",
            "repos_url": "https://api.github.com/users/fdwr/repos",
            "events_url": "https://api.github.com/users/fdwr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fdwr/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-03-01T06:53:48Z",
        "updated_at": "2022-06-23T00:55:01Z",
        "author_association": "MEMBER",
        "body": "@j-paulus Sorry this got buried in the notification noise - I'm cleaning up old issues. :/ I was able to repro seeing a C++ `Ort::Exception::Exception` with ORT 1.10 via the value 768 on Nvidia Quadro P400 (thanks for the repro snippets). The `output_tensors` is size 1, but the contained `Ort::Value` is empty. After enabling the debug layer via dxcpl.exe...\r\n\r\n![image](https://user-images.githubusercontent.com/1809166/156119505-35cef5b0-6b0c-4caa-ac3d-194540898f8e.png)\r\n\r\n...I saw the following output:\r\n\r\n```\r\nD3D12 ERROR: ID3D12Device::RemoveDevice: Device removal has been triggered for the following reason\r\nDXGI_ERROR_DEVICE_HUNG: The Device took an unreasonable amount of time to execute its commands, or the hardware crashed/hung.\r\nAs a result, the TDR (Timeout Detection and Recovery) mechanism has been triggered.\r\nThe current Device Context was executing commands when the hang occurred.\r\nThe application may want to respawn and fallback to less aggressive use of the display hardware).\r\n[ EXECUTION ERROR #232: DEVICE_REMOVAL_PROCESS_AT_FAULT]\r\n```\r\n\r\nI suspect the ConvTranspose is taking too long.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1055086140/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]